---
resource_type:
  - name: npm-cache
    type: docker-image
    source:
      repository: ymedlop/npm-cache-resource
      tags: latest

resources:
  - name: hello_hapi
    type: git
    source: &repo-source
      uri: git@github.com:phapaleganesh/hello-hapi.git
      branch: master
      private_key: |
        -----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABlwAAAAdzc2gtcn
NhAAAAAwEAAQAAAYEAxi/y9lAIWNK5kBy8Sdv+5TX0vOkuQNbQqdEKMIj30pH7hgIg08Pn
TqGZDPnxhm9An8II2y7ol+p7Tmd0a2qhhMq9uSFt1B067AWmE4ngiVki0VZqEUJRtTiCF3
v0ZUsu1aCYQJ7mBZ6rzGDXtUrYfJVgFoXXC8VUusu38xjVCpG9DIss9smMxwC91EXCUHu9
wQN9AULmM3TtRlxDrE06R9gj5Iteq7gX0HHnPKynULqP1E+XpO3EX5UlWeOf3wVOs0vYBQ
E1dCNVIe0eSCFF9nUonHLwJfl/DFyd24jLth5CQKa79RW1zoOHdEylM1/KxWcaoZbOj77k
vA3YTmYuUxsaOSWZVsA7zw2iWE4AWWrmUNdARZkKdPpYJ5b20lGKMB0yz71X9hqQGe7zdC
rmp8eAfLT6mDfoX9fa9L+RnHph3Fyl5R0OmeBbjmgD3oWlPoFJ13CFV/4YEpHYvJQdzfMh
3RtFJ0ughg0pzhQ1ocRucwC62FJxVH9e2Z5QpGFNAAAFkPagXv/2oF7/AAAAB3NzaC1yc2
EAAAGBAMYv8vZQCFjSuZAcvEnb/uU19LzpLkDW0KnRCjCI99KR+4YCINPD506hmQz58YZv
QJ/CCNsu6Jfqe05ndGtqoYTKvbkhbdQdOuwFphOJ4IlZItFWahFCUbU4ghd79GVLLtWgmE
Ce5gWeq8xg17VK2HyVYBaF1wvFVLrLt/MY1QqRvQyLLPbJjMcAvdRFwlB7vcEDfQFC5jN0
7UZcQ6xNOkfYI+SLXqu4F9Bx5zysp1C6j9RPl6TtxF+VJVnjn98FTrNL2AUBNXQjVSHtHk
ghRfZ1KJxy8CX5fwxcnduIy7YeQkCmu/UVtc6Dh3RMpTNfysVnGqGWzo++5LwN2E5mLlMb
GjklmVbAO88NolhOAFlq5lDXQEWZCnT6WCeW9tJRijAdMs+9V/YakBnu83Qq5qfHgHy0+p
g36F/X2vS/kZx6YdxcpeUdDpngW45oA96FpT6BSddwhVf+GBKR2LyUHc3zId0bRSdLoIYN
Kc4UNaHEbnMAuthScVR/XtmeUKRhTQAAAAMBAAEAAAGBAKUI3Lu8HZdJsviM1UZ0Cih469
o8GyYnPA+NYXzVMfmJUvhe4VM2uXFDJB4oLLYUAq6Gd7V9tHZ87j117P5eBy57Xc3CRqDx
zlUoxwlSMUZukY3c9ep1XXEZI0vHDtci6lc+qkp1h3p6jPleU4JGV0w3X5Kh1VeZ9Vqvtf
ibXxy0C8dcRg8j+zTkKy+O/6bhxDvsWbYpLWUAI24J+tiKXtPg6tKwNB+u5zXPBA4EgDe7
g3X66X6P+IzXuAjIgiLHWTBP1tS919T4z5gCjEYhgNOXAKIkT7e3V+mCunF2htSv9iVl7X
KeEvWoWUw7mx28FX6rkk+hMry3mY/CNc45xtFcejDkmZhHa/vgYpaUx7mgslF0m3Dv7+ne
OKaQ8jn7B9GO1q/AmSMYPgEYuEg5g/x1hUxHacr8hK5EWP2nZvPhUNJVn/PmXGfgTbqTKC
Zs3ud4kTnRpUP/JyQNHpCvxRZEhxrwoZ6Jg0eOyu8g/CFQUJ2cq6XSzq//+SB2L1/HwQAA
AMEAlg8RpvzryYc9s+rb2zyRnlbKV1llU5e+9TqnHIHoY7ST7iekZcv1n4cHVLB33gZAjN
JMvtJAvyl86+sAiNDqJXwqIgOp2RcW6iUGtK9czPwLx6CSzJ0tC4HzT6sRzDbFPFW4pOLp
sjQ0qiOkesZIcuBBYitfgfVuXfPhPTJKgkECYsOcDAwZYOz/pnEQF8qLPc22NVqItyEJM/
MW2jqt6sXLyQAcSoK6HX42kpqjHrk7GMLKwLcFrgL2g6UfI09JAAAAwQDtbzKQ9Yf/sqif
BzBLpKsMOdQE6YKziBZ3YUVk0nB7Aqs4C/w9lUDvID/NsqvQ+o0E8piWKn47bJZz/pRwch
w2MLjxnAXZUOin5h9HJ3+MphVKUHVKPzRSU2ghpCv2YTPjYJ7pQXGRGtAI97Ql8W2a97E5
YSyhO7sRPynKJSejg+JBTyf7u02GEx/Di9sdYKPjaWYURc1OThKp/iQjitrHQo9W9rK7lf
0V4GGaD5ANK1JkzXJGg1A7y000bzapF6UAAADBANWvIUouWY8xopwWZ2IN/8XqcJwhI/zd
qC+vGalNuGLTj/QRRieigUH+SkjJ/jgT/7KCQc1WQWwTFLCcamojN/QggWVqIrUvlXw59E
9FHUa6zAsGgw3V/Zr2juF+J5pTiAeZcSD2vZNxDtau1RmCZXE6HY4AuCjimpdnSCWjbU5w
VgcBqPxLQ8OczCLRtsI6YU0sW3/64reV+z4OwPHyDWspKLWsDSDufiQDc/4vnmSDtctvB6
xzfsnPIUhYaP6yiQAAABh1YnVudHVAdWJ1bnR1LVZpcnR1YWxCb3gB
-----END OPENSSH PRIVATE KEY-----
  - name: dependency-cache
    type: npm-cache
    source:
      <<: *repo-source
      paths:
        - package.json

jobs:
  - name: install-dependencies
    plan:
      - get: hello_hapi
        trigger: true
      - get: dependency-cache
  - name: run-tests
    plan:
      - get: hello_hapi
        trigger: true
        passed: [install-dependencies]
      - get: dependency-cache
        passed: [install-dependencies]
      - task: run-the-test-suite
        file: hello_hapi/ci/tasks/run_tests.yml
